spring.redis:
    database: 0
    host: localhost
    port: 6379

spring.session:
    store-type: redis
    timeout: 3000
    redis:
        cleanup-cron: 0 * * * * *
        flush-mode: on-save
        namespace: ssoserver:session